# General parameters
"mode": "Sample"
"run_name": "run_name2"
"output_dir": "/project/scratch/p200177/DE_371/angeliquebonamy/Diffusion/"
"batch_size": 16
"any_time": 1
"use_AMP": false
"compile_model": false
# Sampling parameters
# "n_sampling_conditioning_sets": 4
"n_sampling_conditioning_sets": 4
"ddim_timesteps": 15 #sampler timesteps, more generally. TODO rename to make it not specific to DDIM
"plot": true
"sampling_mode": "conditioned_input"
"random_noise": true
"S_churn": 40
"S_tmin": 0.05
"S_tmax": 50
"S_noise": 1.000
"rho": 9
"n_conditions": 5
# "mean_conditioning": true
# "var_conditioning": true
"leatimes_conditioning": true
# "learn_residue": true
# "predict_residue": true
"reproductibility_seed": 0
# "bootstrap_conditions": false

# Data parameters
"data_dir": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done"
"csv_file": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/Large_lt_val_labels_ens.csv"
# "csv_file": "/home/users/u102230/autres/exemples_labels/3hstep_test_labels_reduced_dev_ens.csv"
"mean_var_dir": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/mean_var_files"
"n_var": 3
"var_indexes": [ "u", "v", "t2m" ]
# date_start: '2020-07-01' # take dates >= date_start
# date_stop: '2020-08-01' # take dates < date_start
# leadtimes: [ 2, 5]
leadtimes: [ 2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44 ]
"crop": [ 0,256,0,256 ]
"orography_conditioning": false
"path_to_orography" : "/project/home/p200177/DE_371/resources/AROME_orography/PEARO_EURW1S40_Orography.npy"
"invert_norm": true
"mean_file": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/Mean_4_var.npy" # is not compatible with dataset_config_file
"max_file": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/Max_4_var.npy" # is not compatible with dataset_config_file
"stat_folder": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/stat_files_Massif_Central"
"rr_transform": LogTransform
"offset_file": mean_rr_log.npy
"scale_file": max_rr_log.npy
"image_size": 256
"guiding_col": "ensemble_id"

# Model parameters
"elucidated_diffusion_sampler": true
"scheduler": "OneCycleLR"
"scheduler_epoch": 250
"resume": false
"epochs": 250
"sigma_min": 0.002
"sigma_max": 80
"sigma_data": 0.5
"P_mean" : -1.2
"P_std": 1.2
"beta_schedule": "linear"
"model_path": "/project/home/p200177/DE_371/maxencelame/models/run_train_conditional_5_conditions_lr_5e05/best.pt"

# Tracking parameters
"wandbproject": "my_project"
"use_wandb": false
"entityWDB": "my_entity"