# General parameters
"mode": "Train"
"run_name": "run_train_1_TEST"
"output_dir": "/project/home/p200177/DE_371/clementbrochet/models"
"batch_size": 16
"any_time": 5

# Sampling parameters (not important while training)
"ddim_timesteps": 10
"plot": true
"sampling_mode": "conditioned"
"n_sample": 4
"random_noise": true
"S_churn": 40
"S_tmin": 0.05
"S_tmax": 50
"S_noise": 1.003
"rho": 7

# Data parameters
"data_dir": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done"
"csv_file": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/Large_lt_train_labels_1_ens_dev.csv"
# "validation": true
# "csv_val_file": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/Large_lt_val_labels_ens.csv"
"mean_var_dir": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/mean_var_files"
"v_i": 4
"var_indexes": ["rr","u", "v", "t2m" ]
"rr": /home/users/u102414/DE371_DiffusionModel/config/ed_4var/rr_dataset_config.yml
"crop": [ 0,256,0,256 ]
"invert_norm": false
"stat_folder": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/stat_files_Massif_Central" # is not compatible with dataset_config_file
"offset_file": mean_rr_log.npy
"scale_file": max_rr_log.npy
"image_size": 256
"guiding_col": "ensemble_id"
"n_conditions": 1
# "mean_conditionning": true
# # "var_conditionning": true

# Model parameters
"elucidated_diffusion_sampler": true
"scheduler": "OneCycleLR"
"scheduler_epoch": 3
"resume": false
"epochs": 3
"sigma_min": 0.002
"sigma_max": 80
"sigma_data": 0.5
"P_mean" : -1.2
"P_std": 1.2
"beta_schedule": "linear"
"lr": 5.0e-05

# Tracking parameters
"use_mlflow": true # activation mlflow log
"ml_tracking_uri": "../mlruns" # path to log mlflow
"ml_experiment_name": "ddpm_dev" # experience name  "wandbproject": "your_wandb_project",
"use_wandb": false
"entityWDB": "your_entity"