# General parameters
"mode": "Train"
"run_name": "run_train_conditional_ED_4var_5_cond"
"output_dir": "/project/scratch/p200177/DE_371/maxencelame/models/"
"batch_size": 16
"any_time": 5

# Sampling parameters (not important while training)
"ddim_timesteps": 10
"plot": true
"sampling_mode": "conditioned"
"n_sample": 4
"random_noise": true
"S_churn": 40
"S_tmin": 0.05
"S_tmax": 50
"S_noise": 1.003
"rho": 7

# Data parameters
"data_dir": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done"
# "data_dir": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France_rr_u_v_t2m/data/IS_rr_debug_1_1.0_0_0_0_0_0_256_large_lt"
"csv_file": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France/IS_1_1.0_0_0_0_0_0_256_large_lt_done/Large_lt_train_labels_1_ens.csv"
# "csv_file": "/project/home/p200177/DE_371/datasets/dataset_Meteo_France_rr_u_v_t2m/data/IS_rr_debug_1_1.0_0_0_0_0_0_256_large_lt/IS_boostrap_no_duplicate_rr_cumul_correct_train.csv"
"n_var": 4
"var_indexes": [ "rr", "u", "v", "t2m" ]
"crop": [ 0,256,0,256 ]
"invert_norm": false
"dataset_config_file": "/home/users/u102230/code/DE371_DiffusionModel/config/ed_4var/rr_dataset_config.yml"   # is not compatible with max_file and mean_file 
"image_size": 256
"guiding_col": "ensemble_id"
"n_conditions": 5

# Model parameters
"elucidated_diffusion_sampler": true
"scheduler": "OneCycleLR"
"scheduler_epoch": 250
"resume": false
"epochs": 250
"sigma_min": 0.002
"sigma_max": 80
"sigma_data": 0.5
"P_mean" : -1.2
"P_std": 1.2
"beta_schedule": "linear"
"lr": 5.0e-05

# Tracking parameters
"use_mlflow": true # activation mlflow log
"ml_tracking_uri": "../mlruns" # path to log mlflow
"ml_experiment_name": "ddpm_dev" # experience name  "wandbproject": "your_wandb_project",
"use_wandb": false
"entityWDB": "your_entity"